// ─── Staff-Level Global Type Augmentations ───
// Extends Express Request to include idempotency key, request ID, and
// other cross-cutting concerns that every middleware and controller needs.

declare namespace Express {
  interface Request {
    /**
     * Unique request ID generated by `requestIdMiddleware`.
     * Used for distributed tracing and log correlation.
     */
    requestId: string;

    /**
     * Idempotency key from the `Idempotency-Key` header.
     * Used to prevent duplicate processing of the same request.
     * Populated by the `idempotencyMiddleware` (Sprint 4).
     */
    idempotencyKey?: string;

    /**
     * Authenticated user identity, populated by auth middleware.
     * Set by the API Gateway or auth-service after JWT verification.
     */
    user?: {
      id: string;
      role: import("../generated/prisma/enums.js").UserRoles[];
      email: string;
    };
  }
}
